import React from 'react';
import './App.css';

function App() {
  return (
    <div className="App">
      <header className="App-header">
        <h1>Welcome to silent-axolotl-flip-1757260374937</h1>
        <p>This app was generated by Applaa</p>
      </header>
    </div>
  );
}

export default App;